### ISSUE TITLE
Downgrade Android gradle plugin for IntelliJ IDEA compatibility

### ISSUE THREAD

**Issue by hrodrick** [rootstrap/FlowForms#9]
### Description
* KMP projects are intended to be developed inside the IntelliJ IDEA IDE, but the current Android Gradle Pluging (AGP) version is too high and is not supported by that IDE.

### Requirements
 * Downgrade AGP to the latest version supported by IntelliJ IDEA

**Comment by Chandra-Sekhar-Bala** [comment]
I think if we change gradle version to 6.1.1+ this will work. 
WDYT?

**Comment by hrodrick** [comment]
Seems good! We may need to change some gradle attributes' names because I think we are using a couple gradle 7 specific ones

**Comment by hrodrick** [comment]
Latest gradle projects requires libs to use Gradle 7.4+ (see https://github.com/rootstrap/FlowForms/issues/51) so this may not be needed anymore and/or needs to be handled carefully

**Comment by hrodrick** [comment]
Closing because we should always strive to support latest gradle build. Which is also a required update over time due to updates in the android gradle plugin and compile sdks.
